steps:
# Build the image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/carlosvalencia-dev/continous/demoimg/testcont:$COMMIT_SHA', '.']
# Push the image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/carlosvalencia-dev/continous/demoimg/testcont:$COMMIT_SHA']
# Deploy image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: 
    - 'run'
    - 'deploy'
    - 'testcont'
    - '--image'
    - 'us-central1-docker.pkg.dev/carlosvalencia-dev/continous/demoimg/testcont:$COMMIT_SHA'
    - '--region'
    - 'SERVICE_REGION'
images:
- 'us-central1-docker.pkg.dev/carlosvalencia-dev/continous/demoimg/testcont:$COMMIT_SHA'
options:
    logging: CLOUD_LOGGING_ONLY
