# ... other trigger configurations
build:
  dockerfile: # This indicates it's using a Dockerfile
    # ... Dockerfile specific settings like path, args etc.
  # You need to add or modify the 'options' here:
  options:
    logging: CLOUD_LOGGING_ONLY
# ... rest of your trigger configuration